### ISSUE TITLE
Dice che nel metodo toResponseDTO() non è possibile invocare order.getVehicle() perché order è nullo

### ISSUE THREAD

**Issue by ilGrandeWorro** [develhope/Java23-Team2-Dealer#57]
https://github.com/develhope/Java23-Team2-Dealer/blob/222422f949d1822bf436330a2aadf5f1e47764df/src/test/java/com/develhope/spring/deals/services/OrderServiceTest.java#L73

**Comment by gabrielD4** [comment]
solved tutti i test vanno

**Comment by gabrielD4** [comment]
solved, tuti i test vanno
