### ISSUE TITLE
Aggiorna il dailyCost solo sul DTO di ritorno, e non sull'entity, contrariamente da come ci si aspetta

### ISSUE THREAD

**Issue by ilGrandeWorro** [develhope/Java23-Team2-Dealer#88]
https://github.com/develhope/Java23-Team2-Dealer/blob/c512e2b28264c2264c7c90ad203f97cab756597f/src/main/java/com/develhope/spring/deals/services/RentalService.java#L62

**Comment by gabrielD4** [comment]
In rental non cè un campo dailyCost quindi è giusto così
